# -----------------FRONT SIDE---------------------------
/:
  controller: Home 
  action: index

# Articles
/articles:
  controller: Articles
  action: allArticles

/article:
  controller: Articles
  action: article
  # ROUTE DYNAMIQUE A FAIRE

# Recettes
/recipes:
  controller: Recipes
  action: allRecipes

/recipe:
  controller: Recipes
  action: recipe
  # ROUTE DYNAMIQUE A FAIRE

# Utilisateur
/register:
  controller: Security
  action: register

/confirm:
  controller: Security
  action: Confirm

/login:
  controller: Security
  action: login

/profil:
  controller: Security
  action: profil

/logout:
  controller: Security
  action: logout 

/contact:
  controller: Security 
  action: contact


# -----------------FRONT SIDE---------------------------

# -----------------BACK SIDE----------------------------
/back-office:
  controller: Dashboard
  action: dashboard
  roles: 
    - Admin
    - Moderateur
    - Editeur

/homepage:
  controller: Dashboard
  action: homepage
  roles:
    - Admin

/recipes-bo:
  controller: Recipes
  action: allRecipesBO
  roles: 
    - Admin
    - Editeur

/create-recipe:
  controller: Recipes
  action: createRecipe
  roles:
    - Admin
    - Editeur

/recipe-bo:
  controller: Recipes
  action: recipeBO
  roles:
    - Admin
    - Editeur
# yes, une route dynamique

/articles-bo:
  controller: Articles
  action: allArticlesBO
  roles:
    - Admin
    - Editeur

/create-article:
  controller: Articles 
  action: createArticle
  roles:
    - Admin
    - Editeur

/article-bo:
  controller: Articles
  action: articleBO
  roles:
    - Admin
    - Editeur
# yes, une route dynamique

/comments-bo:
  controller: Dashboard
  action: comments
  roles:
    - Admin
    - Moderateur

/contact-bo:
  controller: Dashboard
  action: contact
  roles:
    - Admin

# -----------------BACK SIDE----------------------------