# -----------------FRONT SIDE---------------------------
/:
  controller: Home 
  action: index

# Articles
/articles:
  controller: Articles
  action: allArticles

/article:
  controller: Articles
  action: article
  # ROUTE DYNAMIQUE A FAIRE

# Recettes
/recipes:
  controller: Recipes
  action: allRecipes

/recipe:
  controller: Recipes
  action: recipe
  # ROUTE DYNAMIQUE A FAIRE

# Utilisateur
/register:
  controller: Security
  action: register

/confirm:
  controller: Security
  action: Confirm

/login:
  controller: Security
  action: login

/profil:
  controller: Security
  action: profil

/logout:
  controller: Security
  action: logout 

/delete-profil:
  controller: Security
  action: delete

/contact:
  controller: Security 
  action: contact


# -----------------FRONT SIDE---------------------------

# -----------------BACK SIDE----------------------------
/back-office:
  controller: Dashboard
  action: dashboard
  roles: 
    - Admin
    - Moderateur
    - Editeur

/menu:
  controller: Dashboard
  action: menu
  roles:
    - Admin

/create-menu:
  controller: Dashboard 
  action: createMenu
  roles:
    - Admin

/homepage:
  controller: Home
  action: homepage
  roles:
    - Admin

/create-homepage:
  controller: Home 
  action: createHomepage
  roles: 
    - Admin

/recipespage:
  controller: Dashboard
  action: recipespage
  roles:
    - Admin

/create-recipespage:
  controller: Dashboard
  action: createRecipespage
  roles: 
    - Admin

/articlespage:
  controller: Dashboard
  action: articlespage
  roles:
    - Admin

/create-articlespage:
  controller: Dashboard
  action: createArticlespage
  roles: 
    - Admin

/contactpage:
  controller: Dashboard
  action: contact
  roles:
    - Admin

/create-contactpage:
  controller: Dashboard
  action: createContactpage
  roles:
    - Admin

/registerpage:
  controller: Dashboard
  action: register
  roles: 
    - Admin

/create-registerpage:
  controller: Dashboard
  action: createRegister
  roles:
    - Admin 

/loginpage: 
  controller: Dashboard
  action: login
  roles:
    - Admin

/create-loginpage:
  controller: Dashboard
  action: createLogin
  roles:
    - Admin

/profilpage:
  controller: Dashboard
  action: profil 
  roles:
    - Admin

/create-profilpage:
  controller: Dashboard
  action: createProfil
  roles: 
    - Admin


/recipes-bo:
  controller: Recipes
  action: allRecipesBO
  roles: 
    - Admin
    - Editeur

/create-recipe:
  controller: Recipes
  action: createRecipe
  roles:
    - Admin
    - Editeur

/recipe-bo:
  controller: Recipes
  action: recipeBO
  roles:
    - Admin
    - Editeur
# yes, une route dynamique

/delete-recipe:
  controller: Recipes
  action: delete
  roles:
    - Admin
    - Editeur

/articles-bo:
  controller: Articles
  action: allArticlesBO
  roles:
    - Admin
    - Editeur

/create-article:
  controller: Articles 
  action: createArticle
  roles:
    - Admin
    - Editeur

/article-bo:
  controller: Articles
  action: articleBO
  roles:
    - Admin
    - Editeur
# yes, une route dynamique

/delete-article:
  controller: Articles
  action: delete
  roles:
    - Admin
    - Editeur

/users-bo:
  controller: Users
  action: show
  roles:
    - Admin

/user-bo:
  controller: Users
  action: update
  roles:
    - Admin

/delete-user:
  controller: Users
  action: delete
  roles:
    - Admin

/comments-bo:
  controller: Dashboard
  action: comments
  roles:
    - Admin
    - Moderateur

/delete-comments:
  controller: Dashboard
  action: deleteComment
  roles:
    - Admin
    - Moderateur
# -----------------BACK SIDE----------------------------