# -----------------FRONT SIDE---------------------------
/:
  controller: Home 
  action: index

# Articles
/articles:
  controller: Articles
  action: allArticles

/article:
  controller: Articles
  action: article
  # ROUTE DYNAMIQUE A FAIRE

# Recettes
/recipes:
  controller: Recipes
  action: allRecipes

/recipe:
  controller: Recipes
  action: recipe
  # ROUTE DYNAMIQUE A FAIRE

# Utilisateur
/register:
  controller: Security
  action: register

/confirm:
  controller: Security
  action: Confirm

/login:
  controller: Security
  action: login

/profil:
  controller: Security
  action: profil

/logout:
  controller: Security
  action: logout 

/contact:
  controller: Security 
  action: contact


# -----------------FRONT SIDE---------------------------

# -----------------BACK SIDE----------------------------
/back-office:
  controller: Dashboard
  action: dashboard

/back-office/homepage:
  controller: Dashboard
  action: homepage

/back-office/recipes:
  controller: Recipes
  action: allRecipesBO

/back-office/recipe:
  controller: Recipes
  action: recipeBO
# yes, une route dynamique

/back-office/articles:
  controller: Articles
  action: allArticlesBO

/back-office/article:
  controller: Articles
  action: articleBO
# yes, une route dynamique

/back-office/comments:
  controller: Dashboard
  action: comments

/back-office/contact:
  controller: Dashboard
  action: contact

# -----------------BACK SIDE----------------------------