# -----------------FRONT SIDE---------------------------
/:
  controller: Home 
  action: index

# Articles
/articles:
  controller: Article
  action: allArticles

/article/$i:
  # ROUTE DYNAMIQUE A FAIRE

# Recettes
/recipes:
  controller: Recipe
  action: allRecipes

/recipe/$i:
  # ROUTE DYNAMIQUE A FAIRE

# Utilisateur
/register:
  controller: Security
  action: register

/confirm:
  controller: Security
  action: Confirm

/login:
  controller: Security
  action: login

/profil:
  controller: Security
  action: profil

/logout:
  controller: Security
  action: logout 


# -----------------FRONT SIDE---------------------------

# -----------------BACK SIDE----------------------------
# -----------------BACK SIDE----------------------------