# -----------------FRONT SIDE---------------------------
/:
  controller: Home 
  action: index

# Articles
/articles:
  controller: Articles
  action: allArticles

/article:
  controller: Articles
  action: article
  # ROUTE DYNAMIQUE A FAIRE

# Recettes
/recipes:
  controller: Recipes
  action: allRecipes

/recipe:
  controller: Recipes
  action: recipe
  # ROUTE DYNAMIQUE A FAIRE

# Utilisateur
/register:
  controller: Security
  action: register

/confirm:
  controller: Security
  action: Confirm

/login:
  controller: Security
  action: login

/profil:
  controller: Security
  action: profil

/logout:
  controller: Security
  action: logout 

/contact:
  controller: Security 
  action: contact


# -----------------FRONT SIDE---------------------------

# -----------------BACK SIDE----------------------------
/back-office:
  controller: Dashboard
  action: dashboard
  roles: 
    - Admin
    - Moderateur
    - Editeur

/back-office/homepage:
  controller: Dashboard
  action: homepage
  roles:
    - Admin

/back-office/recipes:
  controller: Recipes
  action: allRecipesBO
  roles:
    - Admin
    - Editeur

/back-office/recipe:
  controller: Recipes
  action: recipeBO
  roles:
    - Admin
    - Editeur
# yes, une route dynamique

/back-office/articles:
  controller: Articles
  action: allArticlesBO
  roles:
    - Admin
    - Editeur

/back-office/article:
  controller: Articles
  action: articleBO
  roles:
    - Admin
    - Editeur
# yes, une route dynamique

/back-office/comments:
  controller: Dashboard
  action: comments
  roles:
    - Admin
    - Moderateur

/back-office/contact:
  controller: Dashboard
  action: contact
  roles:
    - Admin

# -----------------BACK SIDE----------------------------