version: "3"

services:
  app:
    build: site
    container_name: ${APP_CONTAINER_NAME}
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./Cookr/:/var/app/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env

  database:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${ADMINER_PORT}:80
    depends_on:
      - database

volumes:
  pgdata: